name: caltracker-kedro-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.4
  - numpy
  - matplotlib
  - seaborn=0.13.2
  - scikit-learn<1.4
  - kedro=0.19.13
  - kedro-viz>=6.7.0
  - jupyterlab>=3.0
  - ipython>=8.10
  - setuptools
  - gcsfs
  - pip
  - pip:
      - pycaret==3.3.2
      - kedro-datasets>=3.0

