target_column: Calories
# Compute mutual information scores against the correct target
top_features: 4 # Weight column excluded

# Data split ratio for training vs. testing
train_size: 0.8
# Seed for experiment reproducibility
session_id: 42
# Number of top models to compare by MAE
n_models: 5
# Model identifier for hyperparameter tuning
best_model_name: lightgbm
# Path to save the final trained model
model_save_path: data/06_models/final_model.pkl
