target_column: Calories

# Data split ratio for training vs. testing
train_size: 0.8
# Seed for experiment reproducibility
session_id: 42
# Number of top models to compare by MAE
n_models: 3
# Path to save the final trained model
model_save_path: data/06_models/final_model.pkl
